### Get all data
GET http://localhost/PHP/HTTP-Crud/index.php

### Add data
POST http://localhost/PHP/HTTP-Crud/index.php
Content-Type: application/json

{
    "name": "Corona 3",
    "alcohol": 4.5,
    "idBrand": 2
}

### Update data
PUT http://localhost/PHP/HTTP-Crud/index.php
Content-Type: application/json

{
    "id": 2,
    "name": "Jose Sissa",
    "alcohol": 4.5
}

### Delete data
DELETE http://localhost/PHP/HTTP-Crud/index.php?id=2