### Get all data
GET http://localhost/PHP/HTTP-Crud/index.php

### Add data
POST http://localhost/PHP/HTTP-Crud/index.php
Content-Type: application/json

{
    "name": "John Doe"
}

### Update data
PUT http://localhost/PHP/HTTP-Crud/index.php
Content-Type: application/json

{
    "id": 1,
    "name": "Jose Sissa"
}

### Delete data
DELETE http://localhost/PHP/HTTP-Crud/index.php?id=1